[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore:tagMap is deprecated:DeprecationWarning:ldap3\.utils\.asn1
    ignore:typeMap is deprecated:DeprecationWarning:ldap3\.utils\.asn1
    ignore:'oneOf' deprecated:pyparsing.exceptions.PyparsingDeprecationWarning:matplotlib\._fontconfig_pattern
    ignore:'parseString' deprecated:pyparsing.exceptions.PyparsingDeprecationWarning:matplotlib\._fontconfig_pattern
    ignore:'resetCache' deprecated:pyparsing.exceptions.PyparsingDeprecationWarning:matplotlib\._fontconfig_pattern
    ignore:'enablePackrat' deprecated:pyparsing.exceptions.PyparsingDeprecationWarning:matplotlib\._mathtext
