apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pvc.yaml
- postgresql.yaml
- deployment.yaml
images:
- name: desalvo/cybersecurity-incident-registry
  newName: desalvo/cybersecurity-incident-registry
  digest: sha256:dbade42a5aa23551c63e4893f96efb69743aebc33cef1753f5c6545bbdccb5b3
