apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: cir-uploads}
spec:
  accessModes: [ReadWriteOnce]
  resources: {requests: {storage: 5Gi}}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: cir-form-templates}
spec:
  accessModes: [ReadWriteMany]
  resources: {requests: {storage: 1Gi}}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: cir-sso-logos}
spec:
  accessModes: [ReadWriteMany]
  resources: {requests: {storage: 100Mi}}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: cir-ssl-certs}
spec:
  accessModes: [ReadWriteOnce]
  resources: {requests: {storage: 100Mi}}
